name: Version Bump & Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Bump version and generate changelog
        run: |
          cz bump --yes --changelog

      - name: Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "ci: bump version and generate changelog [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
