name: Version Bump & Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Bump version and generate changelog
        run: |
          git config user.name "Moises Navarro"
          git config user.email "moisalejandro@gmail.com"
          cz bump

      - name: Push changes
        run: |
          git push -f
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current version
        id: version
        run: echo "::set-output name=VERSION::$(cz version --project)"

      - name: Extract changelog for release
        id: changelog
        run: |
          echo "::set-output name=CHANGELOG::$(cz changelog --dry-run --unreleased --stdout)"
        shell: bash

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          release_name: v${{ steps.version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
